# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix
shell.
GMAIL_USERNAME: praveencsein@gmail.com
GMAIL_PASSWORD: hello123
MAILCHIMP_API_KEY: 9a27b4c414ee84f4f5bbed4fea971933-us15
MAILCHIMP_LIST_ID: PRAVEEN K T 
DOMAIN_NAME: example.com
OWNER_EMAIL: praveencsein@gmail.com
